/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;
//import javax.swing.JFrame;

import javax.swing.JOptionPane;
//import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.*; 
import java.sql.PreparedStatement;
//import java.sql.DriverManager;

/**
 *
 * @author Alok Kumar
 */

public class LoginPage1 extends javax.swing.JFrame {

    /**
     * Creates new form SignupPage
     */
    public LoginPage1() {
        initComponents();
    }
    
    //method to insert values into users
//    public void insertSignupDetails(){
//        String name = txt_username.getText();
//        String pwd  = txt_password.getText();
//        String email  = txt_email.getText();
//        String contact = txt_contact.getText();
//         try{
//            Connection con = DBconnection.getConnection();
//            String sql = "insert into users(name,password,email,contact) values(?,?,?,?)";
//            PreparedStatement pst = con.prepareStatement(sql);
//            pst.setString(1,name);
//            pst.setString(2,pwd);
//            pst.setString(3,email);
//            pst.setString(4,contact);
//            
//            int updatedRowCount = pst.executeUpdate();
//            if(updatedRowCount>0){
//                JOptionPane.showMessageDialog(this,"Record inserted");
//            }
//            else{
//                JOptionPane.showMessageDialog(this," Failed Record inserted");
//            }
//            
//        }
//        catch(Exception e){
//            e.printStackTrace();
//            
//        }
//    }
    
    //validation
//    public boolean validateSignup(){
//        String name = txt_username.getText();
//        String pwd  = txt_password.getText();
//        String email  = txt_email.getText();
//        String contact = txt_contact.getText();
//        if(name.equals("")){
//            JOptionPane.showMessageDialog(this,"please enter username");
//            return false;
//        }
//        if(pwd.equals("")){
//            JOptionPane.showMessageDialog(this,"please enter valid password");
//            return false;
//        }
//        if(email.equals("") || !email.matches("^.+@.+\\..+$")){
//            JOptionPane.showMessageDialog(this,"please enter valid email id");
//            return false;
//        }
//        if(contact.equals("")){
//            JOptionPane.showMessageDialog(this,"please enter valid contact number");
//            return false;
//        }
//        return true;
//        
//    }
    //checks for duplicates user
//    public boolean checkDuplicateUser(){
//        boolean isExists = false;
//        String name = txt_username.getText();
//        try{
//            Connection con = DBconnection.getConnection();
//            PreparedStatement pst = con.prepareStatement("select * from users where name = ?");
//            pst.setString(1, name);
//            ResultSet rs = pst.executeQuery();
//            if(rs.next()){
//                isExists = true;
//            }
//            else{
//                isExists = false;
//            }
//            
//            
//        }
//        catch(Exception e){
//            e.printStackTrace();
//            
//        }
//        return isExists;
//    }
    
    
    //validation method
    public boolean validateLogin(){
        String name = txt_username.getText();
        String pwd  = txt_password.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(this, "please enter valid username");
        }
        if(pwd.equals("")){
            JOptionPane.showMessageDialog(this, "please enter valid password");
        }
        return true;
    }
    
    public void login(){
        String name = txt_username.getText();
        String pwd  = txt_password.getText();
        try {
            Connection con = DBconnection.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from users where name = ? and password = ?");
            pst.setString(1, name);
            pst.setString(2, pwd);
            
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "login successful");
                homepage home  = new homepage();
                home.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "incorrect username or password");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        signup_panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_username = new app.bolivia.swing.JCTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCTextField2 = new app.bolivia.swing.JCTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jCTextField3 = new app.bolivia.swing.JCTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jCTextField4 = new app.bolivia.swing.JCTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jCTextField5 = new app.bolivia.swing.JCTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jCTextField6 = new app.bolivia.swing.JCTextField();
        jLabel32 = new javax.swing.JLabel();
        txt_password = new app.bolivia.swing.JCTextField();
        jLabel33 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jCTextField8 = new app.bolivia.swing.JCTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jCTextField9 = new app.bolivia.swing.JCTextField();
        jLabel42 = new javax.swing.JLabel();
        jCTextField10 = new app.bolivia.swing.JCTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jCTextField11 = new app.bolivia.swing.JCTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jCTextField12 = new app.bolivia.swing.JCTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jCTextField14 = new app.bolivia.swing.JCTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jCTextField15 = new app.bolivia.swing.JCTextField();
        jLabel62 = new javax.swing.JLabel();
        jCTextField16 = new app.bolivia.swing.JCTextField();
        jLabel63 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jCTextField17 = new app.bolivia.swing.JCTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jCTextField18 = new app.bolivia.swing.JCTextField();
        jLabel72 = new javax.swing.JLabel();
        jCTextField19 = new app.bolivia.swing.JCTextField();
        jLabel73 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jCTextField20 = new app.bolivia.swing.JCTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jCTextField21 = new app.bolivia.swing.JCTextField();
        txt_login = new rojerusan.RSMaterialButtonCircle();
        txt_signup = new rojerusan.RSMaterialButtonCircle();
        jLabel84 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Central Library");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("DEVELOPER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 20));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("PHENOMENAL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("PHENOMENAL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Welcome To");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/library-3.png.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 120, 740, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 830));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("PHENOMENAL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        signup_panel.setBackground(new java.awt.Color(0, 0, 255));
        signup_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username");
        signup_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel9.setFont(new java.awt.Font("MS PGothic", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        signup_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        signup_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        txt_username.setBackground(new java.awt.Color(0, 0, 255));
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_username.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_username.setPlaceholder("Enter Username...");
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        signup_panel.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Username");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel13.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Signup Page");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Create New Account Here");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField2.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField2.setPlaceholder("Enter Username...");
        jCTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        signup_panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 620, 830));

        jPanel4.setBackground(new java.awt.Color(0, 0, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Username");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel17.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Signup Page");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Create New Account Here");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField3.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField3.setPlaceholder("Enter Username...");
        jCTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField3ActionPerformed(evt);
            }
        });
        jPanel4.add(jCTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Username");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel21.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Signup Page");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Create New Account Here");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField4.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField4.setPlaceholder("Enter Username...");
        jCTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField4ActionPerformed(evt);
            }
        });
        jPanel5.add(jCTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 620, 830));

        signup_panel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 620, 830));

        jPanel6.setBackground(new java.awt.Color(0, 0, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Username");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel25.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Signup Page");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Create New Account Here");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField5.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField5.setPlaceholder("Enter Username...");
        jCTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField5ActionPerformed(evt);
            }
        });
        jPanel6.add(jCTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Username");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel29.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Signup Page");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Create New Account Here");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField6.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField6.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField6.setPlaceholder("Enter Username...");
        jCTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField6ActionPerformed(evt);
            }
        });
        jPanel7.add(jCTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 620, 830));

        signup_panel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 620, 830));

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Secure_50px.png"))); // NOI18N
        signup_panel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, 60));

        txt_password.setBackground(new java.awt.Color(0, 0, 255));
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_password.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_password.setPlaceholder("Enter Password...");
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        signup_panel.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Password");
        signup_panel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, 20));

        jPanel8.setBackground(new java.awt.Color(0, 0, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Username");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel35.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Signup Page");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Create New Account Here");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel37.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField8.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField8.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField8.setPlaceholder("Enter Username...");
        jCTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField8ActionPerformed(evt);
            }
        });
        jPanel8.add(jCTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jPanel9.setBackground(new java.awt.Color(0, 0, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Username");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel39.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Signup Page");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel40.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Create New Account Here");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel41.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField9.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField9.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField9.setPlaceholder("Enter Username...");
        jCTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField9ActionPerformed(evt);
            }
        });
        jPanel9.add(jCTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 620, 830));

        signup_panel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 620, 830));

        jLabel42.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        signup_panel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField10.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField10.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField10.setPlaceholder("Enter Username...");
        jCTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField10ActionPerformed(evt);
            }
        });
        signup_panel.add(jCTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel43.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Username");
        signup_panel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jPanel10.setBackground(new java.awt.Color(0, 0, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Username");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel45.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Signup Page");
        jPanel10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel46.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Create New Account Here");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel47.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel10.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField11.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField11.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField11.setPlaceholder("Enter Username...");
        jCTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField11ActionPerformed(evt);
            }
        });
        jPanel10.add(jCTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jPanel11.setBackground(new java.awt.Color(0, 0, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Username");
        jPanel11.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel49.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Signup Page");
        jPanel11.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel50.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Create New Account Here");
        jPanel11.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel51.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel11.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField12.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField12.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField12.setPlaceholder("Enter Username...");
        jCTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField12ActionPerformed(evt);
            }
        });
        jPanel11.add(jCTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 620, 830));

        signup_panel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 180, 620, 830));

        jPanel12.setBackground(new java.awt.Color(0, 0, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Username");
        jPanel12.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel55.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Signup Page");
        jPanel12.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel56.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Create New Account Here");
        jPanel12.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel57.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel12.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField14.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField14.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField14.setPlaceholder("Enter Username...");
        jCTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField14ActionPerformed(evt);
            }
        });
        jPanel12.add(jCTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jPanel13.setBackground(new java.awt.Color(0, 0, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Username");
        jPanel13.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel59.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Signup Page");
        jPanel13.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel60.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Create New Account Here");
        jPanel13.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel61.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel13.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField15.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField15.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField15.setPlaceholder("Enter Username...");
        jCTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField15ActionPerformed(evt);
            }
        });
        jPanel13.add(jCTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 620, 830));

        signup_panel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 620, 830));

        jLabel62.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        signup_panel.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField16.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField16.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField16.setPlaceholder("Enter Username...");
        jCTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField16ActionPerformed(evt);
            }
        });
        signup_panel.add(jCTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel63.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Username");
        signup_panel.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jPanel14.setBackground(new java.awt.Color(0, 0, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel64.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Username");
        jPanel14.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel65.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Signup Page");
        jPanel14.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel66.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Create New Account Here");
        jPanel14.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel67.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel14.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField17.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField17.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField17.setPlaceholder("Enter Username...");
        jCTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField17ActionPerformed(evt);
            }
        });
        jPanel14.add(jCTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jPanel15.setBackground(new java.awt.Color(0, 0, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Username");
        jPanel15.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel69.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Signup Page");
        jPanel15.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel70.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Create New Account Here");
        jPanel15.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel71.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel15.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField18.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField18.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField18.setPlaceholder("Enter Username...");
        jCTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField18ActionPerformed(evt);
            }
        });
        jPanel15.add(jCTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 620, 830));

        signup_panel.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 620, 830));

        jLabel72.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        signup_panel.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField19.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField19.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField19.setPlaceholder("Enter Username...");
        jCTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField19ActionPerformed(evt);
            }
        });
        signup_panel.add(jCTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel73.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Username");
        signup_panel.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jPanel16.setBackground(new java.awt.Color(0, 0, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel74.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Username");
        jPanel16.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel75.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Signup Page");
        jPanel16.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel76.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Create New Account Here");
        jPanel16.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel77.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel16.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField20.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField20.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField20.setPlaceholder("Enter Username...");
        jCTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField20ActionPerformed(evt);
            }
        });
        jPanel16.add(jCTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jPanel17.setBackground(new java.awt.Color(0, 0, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel78.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("Username");
        jPanel17.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 20));

        jLabel79.setFont(new java.awt.Font("MS PGothic", 1, 25)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Signup Page");
        jPanel17.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel80.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Create New Account Here");
        jPanel17.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        jLabel81.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel17.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 60));

        jCTextField21.setBackground(new java.awt.Color(0, 0, 255));
        jCTextField21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField21.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField21.setPlaceholder("Enter Username...");
        jCTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField21ActionPerformed(evt);
            }
        });
        jPanel17.add(jCTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 620, 830));

        signup_panel.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 270, 620, 830));

        txt_login.setBackground(new java.awt.Color(0, 0, 153));
        txt_login.setText("LOGIN");
        txt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loginActionPerformed(evt);
            }
        });
        signup_panel.add(txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 330, 70));

        txt_signup.setBackground(new java.awt.Color(255, 0, 51));
        txt_signup.setText("SIGNUP");
        txt_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_signupActionPerformed(evt);
            }
        });
        signup_panel.add(txt_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 330, 70));

        jLabel84.setFont(new java.awt.Font("MS PGothic", 1, 35)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Login Page");
        signup_panel.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        getContentPane().add(signup_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 700, 830));

        setSize(new java.awt.Dimension(1361, 748));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void jCTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField2ActionPerformed

    private void jCTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField3ActionPerformed

    private void jCTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField4ActionPerformed

    private void jCTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField5ActionPerformed

    private void jCTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField6ActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void jCTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField8ActionPerformed

    private void jCTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField9ActionPerformed

    private void jCTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField10ActionPerformed

    private void jCTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField11ActionPerformed

    private void jCTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField12ActionPerformed

    private void jCTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField14ActionPerformed

    private void jCTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField15ActionPerformed

    private void jCTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField16ActionPerformed

    private void jCTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField17ActionPerformed

    private void jCTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField18ActionPerformed

    private void jCTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField19ActionPerformed

    private void jCTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField20ActionPerformed

    private void jCTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField21ActionPerformed

    private void txt_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_signupActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_signupActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
       
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loginActionPerformed
        // TODO add your handling code here:
        
        if (validateLogin()==true){
            login();
        }
    }//GEN-LAST:event_txt_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField jCTextField10;
    private app.bolivia.swing.JCTextField jCTextField11;
    private app.bolivia.swing.JCTextField jCTextField12;
    private app.bolivia.swing.JCTextField jCTextField14;
    private app.bolivia.swing.JCTextField jCTextField15;
    private app.bolivia.swing.JCTextField jCTextField16;
    private app.bolivia.swing.JCTextField jCTextField17;
    private app.bolivia.swing.JCTextField jCTextField18;
    private app.bolivia.swing.JCTextField jCTextField19;
    private app.bolivia.swing.JCTextField jCTextField2;
    private app.bolivia.swing.JCTextField jCTextField20;
    private app.bolivia.swing.JCTextField jCTextField21;
    private app.bolivia.swing.JCTextField jCTextField3;
    private app.bolivia.swing.JCTextField jCTextField4;
    private app.bolivia.swing.JCTextField jCTextField5;
    private app.bolivia.swing.JCTextField jCTextField6;
    private app.bolivia.swing.JCTextField jCTextField8;
    private app.bolivia.swing.JCTextField jCTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel signup_panel;
    private rojerusan.RSMaterialButtonCircle txt_login;
    private app.bolivia.swing.JCTextField txt_password;
    private rojerusan.RSMaterialButtonCircle txt_signup;
    private app.bolivia.swing.JCTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
